export const componentList = [
  {
    id: 'button',
    name: '按钮',
    description: '可点击的按钮组件',
    type: 'rect',
    props: {
      width: 100,
      height: 36,
      fill: '#0891B2',
      cornerRadius: 8,
      fontSize: 14,
      fontFamily: 'Inter',
      textColor: '#FFFFFF',
    },
  },
  {
    id: 'input',
    name: '输入框',
    description: '文本输入区域',
    type: 'rect',
    props: {
      text: '',
      placeholder: '请输入...',
      width: 200,
      height: 40,
      fill: '#FFFFFF',
      stroke: '#E2E8F0',
      strokeWidth: 1,
      cornerRadius: 8,
      fontSize: 14,
      fontFamily: 'Inter',
      fontWeight: '400',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'left',
      lineHeight: 1.4,
      textColor: '#0F172A',
    },
  },
  {
    id: 'text',
    name: '文本',
    description: '文字内容',
    type: 'text',
    props: {
      text: '文本内容',
      fontSize: 16,
      fontFamily: 'Inter',
      fontWeight: '400',
      fontStyle: 'normal',
      textDecoration: 'none',
      align: 'left',
      lineHeight: 1.4,
      fill: '#0F172A',
      width: 150,
    },
  },
  {
    id: 'image',
    name: '图片',
    description: '图片占位符',
    type: 'rect',
    props: {
      width: 120,
      height: 80,
      fill: '#F1F5F9',
      stroke: '#E2E8F0',
      strokeWidth: 1,
      cornerRadius: 8,
    },
  },
  {
    id: 'rectangle',
    name: '矩形',
    description: '矩形形状',
    type: 'rect',
    props: {
      width: 120,
      height: 80,
      fill: '#E0F2FE',
      stroke: '#0891B2',
      strokeWidth: 1,
      cornerRadius: 8,
      fontSize: 14,
      fontFamily: 'Inter',
      textColor: '#0F172A',
    },
  },
  {
    id: 'circle',
    name: '圆形',
    description: '圆形形状',
    type: 'circle',
    props: {
      radius: 40,
      fill: '#DCFCE7',
      stroke: '#22C55E',
      strokeWidth: 1,
      fontSize: 14,
      fontFamily: 'Inter',
      textColor: '#0F172A',
    },
  },
  {
    id: 'line',
    name: '线条',
    description: '直线段',
    type: 'line',
    props: {
      points: [0, 0, 100, 0],
      stroke: '#64748B',
      strokeWidth: 2,
    },
  },
];
